id: PE42ABE24
initial_creation_type: ocr
source_metadata:
  volumes:
    23af4eb6284e439fa3f967d22bf3fd9b:
      base_file: v074.txt
      image_group_id: I1PD95919
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་གཞི་བསྡུ་བ།
      total_pages: 1618
      volume_number: 74
