id: PE42ABE24
initial_creation_type: ocr
source_metadata:
  volumes:
    bb8750d9787f432aa545da9af17cdb09:
      base_file: v074.txt
      image_group_id: I1PD95919
      title: རྣལ་འབྱོར་སྤྱོད་པའི་ས་ལས་གཞི་བསྡུ་བ།
      total_pages: 1618
      volume_number: 74
